[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "lerobot_teleoperator_icubteleop"
version = "0.1.0"
description = "Mujoco-based Teleoperator for iCub Robot integrated with Lerobot"
readme = "README.md"
requires-python = ">=3.10"

# Dependencias de Python puro que pip puede instalar sin problemas.
dependencies = [
    "lerobot",
    "numpy",
    "torch",
    "mujoco",
    "glfw",
    "pyyaml"
]

# # --- Puntos de Entrada (Crucial para Lerobot) ---
# # Esto registra tu clase de configuración en el sistema de plugins de Lerobot.
# # Sintaxis: nombre_identificador = "paquete.archivo:ClaseConfig"
[project.entry-points."lerobot.robot_devices.teleoperators"]
icub_teleop_mujoco = "lerobot_teleoperator_icubteleop.config_icubteleop:iCubTeleopConfig"
lerobot_teleoperator_icubteleop = "lerobot_teleoperator_icubteleop.config_icubteleop:iCubTeleopConfig"

# Configuración para encontrar el paquete automáticamente
[tool.setuptools.packages.find]
where = ["."]
include = ["lerobot_teleoperator_icubteleop*"]
exclude = ["*.egg-info"]