robot_name: "icubSim"
period: 0.02
show_cameras: true

# Calidad JPEG del streaming a los lentes VR (0-100, mas alto = mejor calidad / mas ancho de banda)
stream_jpeg_quality: 70

# Configuración de Control: 'left', 'right', 'both' o 'none'
control_arms: "both" 
primary_arm: "right_arm"
gaze_ctrl: true
strict_xml_init: true

# Definición de articulaciones por parte
actuators:
  head:
    - "neck_pitch"
    - "neck_roll"
    - "neck_yaw"
  torso: 
    - "torso_pitch"
    - "torso_roll"
    - "torso_yaw"
  left_arm: 
    - "l_shoulder_pitch"
    - "l_shoulder_roll"
    - "l_shoulder_yaw"
    - "l_elbow"
    - "l_wrist_prosup"
    - "l_wrist_pitch"
    - "l_wrist_yaw"
    - "l_hand_finger"
    - "l_thumb_oppose"
    - "l_thumb_proximal"
    - "l_thumb_distal"
    - "l_index_proximal"
    - "l_index_distal"
    - "l_middle_proximal"
    - "l_middle_distal"
    - "l_pinky"
  right_arm: 
    - "r_shoulder_pitch"
    - "r_shoulder_roll"
    - "r_shoulder_yaw"
    - "r_elbow"
    - "r_wrist_prosup"
    - "r_wrist_pitch"
    - "r_wrist_yaw"
    - "r_hand_finger"
    - "r_thumb_oppose"
    - "r_thumb_proximal"
    - "r_thumb_distal"
    - "r_index_proximal"
    - "r_index_distal"
    - "r_middle_proximal"
    - "r_middle_distal"
    - "r_pinky"

#Pose segura (grados)
home_pose:
  torso_pitch: 0.0
  torso_roll: 0.0
  torso_yaw: 0.0
  l_shoulder_pitch: -10.0
  l_shoulder_roll: 15.0
  l_shoulder_yaw: 0.0
  l_elbow: 80.0
  l_wrist_prosup: 0.0
  l_wrist_pitch: 0.0
  l_wrist_yaw: 0.0
  r_shoulder_pitch: -10.0
  r_shoulder_roll: 15.0
  r_shoulder_yaw: 0.0
  r_elbow: 80.0
  r_wrist_prosup: 0.0
  r_wrist_pitch: 0.0
  r_wrist_yaw: 0.0
  neck_pitch: 0.0
  neck_roll: 0.0
  neck_yaw: 0.0
  eyes_tilt: 0.0
  eyes_version: 0.0
  eyes_vergence: 0.0


# home_pose:
#   torso_pitch: 0.0
#   torso_roll: 0.0
#   torso_yaw: 0.0
#   l_shoulder_pitch: 0.0
#   l_shoulder_roll: 34.4
#   l_shoulder_yaw: 8.9
#   l_elbow: 74.5
#   l_wrist_prosup: 49.3
#   l_wrist_pitch: 0.0
#   l_wrist_yaw: 0.0
#   r_shoulder_pitch: 0.0
#   r_shoulder_roll: 34.4
#   r_shoulder_yaw: 8.9
#   r_elbow: 74.5
#   r_wrist_prosup: 49.3
#   r_wrist_pitch: 0.0
#   r_wrist_yaw: 0.0
#   neck_pitch: 0.0
#   neck_roll: 0.0
#   neck_yaw: 0.0
#   eyes_tilt: 0.0
#   eyes_version: 0.0
#   eyes_vergence: 0.0

hand_open_values:
  - [0, 75, 0, 0, 0, 0, 0, 0, 0]
hand_close_values:
  - [60, 40, 10, 70, 50, 120, 60, 100, 160]

cube_spawn:
  x: [0.35, 0.45]
  y: [-0.15, -0.05]
  z: 0.627
